### ISSUE TITLE
你好，环境搭建起来了，报错，帮忙确认下是否是版本问题呢

### ISSUE THREAD

**Issue by liuchang0403** [Prinsphield/Wechat_AutoJump#100]
我用的版本 python3 opencv3 tensorflow1.5 报错如下
![image](https://user-images.githubusercontent.com/13446218/35379078-df020f5c-01ef-11e8-9901-7550017e5cae.png)

**Comment by Prinsphield** [comment]
不是环境的问题，是没有获取到截图。

Android手机请确认一下`adb devices`有设备，IPhone请按照readme里的流程做准备工作。

**Comment by liuchang0403** [comment]
谢谢，问题已经解决，是因为没有配置 adb 环境变量。多谢
