### ISSUE TITLE
运行出错，AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Tochase** [Prinsphield/Wechat_AutoJump#104]
![image](https://user-images.githubusercontent.com/15307280/35476143-2c77fb14-03e6-11e8-82d6-e89d62163ca6.png)

你好，如图所示，模型恢复成功，最后报错，
AttributeError: 'NoneType' object has no attribute 'shape'
应该是说pivot没有shape属性

特此请教下这个问题要怎样解决？

**Comment by leon332157** [comment]
@Tochase 用python3试试吧

**Comment by Prinsphield** [comment]
没获取到手机截图，自行检查一下

**Comment by Tochase** [comment]
@leon332157 感谢您的答复。
![image](https://user-images.githubusercontent.com/15307280/35479748-68a52e60-0439-11e8-9d3d-de5405396f1b.png)
我使用的 python 就是用 anaconda 装的 3.5.4 版本

**Comment by leon332157** [comment]
@Tochase 你可以尝试使用原生python吗，就是官网下载安装包的，因为一般情况下adb不会出问题吧

**Comment by Tochase** [comment]
@Prinsphield 感谢您的回复，获取截图没有问题。

**Comment by Tochase** [comment]
@leon332157 
感谢您的回复。

已经找到问题了，我下载好模型后，把默认路径修改为resource/train_logs,刚把路径改回来就好了。

**Comment by leon332157** [comment]
@Tochase 好的

**Comment by leon332157** [comment]
@Prinsphield close吧
