### ISSUE TITLE
苹果7刷榜无法成功

### ISSUE THREAD

**Issue by aqnaruto** [Prinsphield/Wechat_AutoJump#109]
如题，最近有空，用肾7 跑了下。这次能上500多分，然而，结束后提示 存在可疑操作，跑了白跑。

估计检测程序应该是检测间隔时间，因为我两百多的时候手动掐了，依然提示 存在可疑操作。
补充，在我机器上并没有跳的非常准，每次都是偏中心点一点点，但是依然被检测到

**Comment by aqnaruto** [comment]
我不是写python的，找到这个应该是函数 改了
`s.tap_hold(random.uniform(0, 320), random.uniform(64, 320), press_time)`
正在跑，希望能成功。

**Comment by aqnaruto** [comment]
改了代码后，刚刚掐了，成功了，希望答主不要更新这个了，否则腾讯会升级小程序检测程序。以上就作为一个门槛吧。看到这个issue的人 才能成功刷榜。不得不佩服我自己学习python的速度和debug检测的速度 哈哈哈哈

**Comment by leon332157** [comment]
@aqnaruto PR一下我看看

**Comment by triplekiller** [comment]
@aqnaruto 分享下代码看看？

**Comment by sjditadmin** [comment]
def jump(self, player_pos, target_pos):
        distance = np.linalg.norm(player_pos - target_pos)
        press_time = distance * self.sensitivity
        press_time = int(np.rint(press_time))
        press_h, press_w = int(0.82*self.resolution[0]), self.resolution[1]//2
        press_h += np.random.randint(-30,30)
        press_w += np.random.randint(-30,30)
        if self.phone == 'Android':
            cmd = 'adb shell input swipe {} {} {} {} {}'.format(press_w, press_h, press_w, press_h, press_time)
            print(cmd)
            os.system(cmd)
        elif self.phone == 'IOS':
            self.s.tap_hold(press_w, press_h, press_time / 1000.)亲测有效

**Comment by Ahdw** [comment]
就算改了随机值，分数超过1000还是被发现啦
