### ISSUE TITLE
iOS设备下  运行python nn_play.py --phone IOS --sensitivity 2.045提示错误如下

### ISSUE THREAD

**Issue by Pcookie** [Prinsphield/Wechat_AutoJump#116]
==== successfully restored ====
Traceback (most recent call last):
  File "nn_play.py", line 211, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.serverURL, args.debug, args.resource)
  File "nn_play.py", line 50, in __init__
    import wda
ImportError: No module named wda

但我Facebook的wda运行成功了  在网页上能看到json输出  不知道py的wda是指这个还是指的别的库？

**Comment by Prinsphield** [comment]
https://testerhome.com/topics/7220
