### ISSUE TITLE
棋盘中心点坐标获取

### ISSUE THREAD

**Issue by JA030019** [Prinsphield/Wechat_AutoJump#119]
你好，我看到你处理过的图像名为state_000_res_h_608_w_446，请问这个目标点的坐标是如何获取的呢？是用了什么工具吗？

**Comment by Prinsphield** [comment]
知乎专栏有详细的介绍，https://zhuanlan.zhihu.com/p/32636329

用的multiscale-search、fast-search算法跑的。
