### ISSUE TITLE
关于跳的不准的问题

### ISSUE THREAD

**Issue by LBAWMY** [Prinsphield/Wechat_AutoJump#13]
刚刚跑了一下楼主的代码，可以正常运行，好像都跳的不准，不知道是楼主修改代码了还是我手机的问题？

**Comment by Prinsphield** [comment]
可能需要调一下`--sensitivity`

**Comment by WangXin93** [comment]
我的iphone6跳的不准，sensitivity试了2.0到2.60，间隔取1.0，最多跳到70，最差的出门就死了，play.py和nn_play.py都存在这个问题，是手机型号的问题吗？

**Comment by jirujun** [comment]
如果你的分辨率高度超过了1280，应该是分辨率的问题，我提交了FIX，官方还没合并，您可以试一下。
