### ISSUE TITLE
代码咨询

### ISSUE THREAD

**Issue by songjiang951130** [Prinsphield/Wechat_AutoJump#15]
press_h, press_w = int(0.82*self.resolution[0]), self.resolution    [1]//2           
cmd = 'adb shell input swipe {} {} {} {} {}'.format(press_w, pre    ss_h, press_w, press_h, press_time)
这段代码是按压点？
在play.py的120行左右

控制台信息
adb: error: failed to get feature set: no devices/emulators found
fast-search, step: 0079
adb shell input swipe 540 1574 540 1574 602
error: no devices/emulators found
error: no devices/emulators found
adb: error: failed to get feature set: no devices/emulators found
fast-search, step: 0080
adb shell input swipe 540 1574 540 1574 602
error: no devices/emulators found
error: no devices/emulators found
adb: error: failed to get feature set: no devices/emulators found
fast-search, step: 0081
adb shell input swipe 540 1574 540 1574 602
error: no devices/emulators found
error: no devices/emulators found
adb: error: failed to get feature set: no devices/emulators found
fast-search, step: 0082
adb shell input swipe 540 1574 540 1574 602

540 1574 540 1574 这个数字是定值啊？

**Comment by Prinsphield** [comment]
是的，这个点是为了死了之后可以继续重新开始
