### ISSUE TITLE
直接下载程序运行，为啥我就跳的不准了，缺哪里了

### ISSUE THREAD

**Issue by reaIws** [Prinsphield/Wechat_AutoJump#17]

**Comment by Prinsphield** [comment]
给点具体信息

**Comment by reaIws** [comment]
1.github上下载代码
2.装python3.6，tensorflow opencv adb
3.运行python play.py --phone Android --sensitivity 2.045

**Comment by reaIws** [comment]
而且经常跳的近

**Comment by Prinsphield** [comment]
那你可以调大一些`--sensitivity`试试

**Comment by reaIws** [comment]
但是有时候跳的准。。。

**Comment by reaIws** [comment]
情况不多

**Comment by reaIws** [comment]
这个--sensitivity应该是固定的吧，微信小程序写死了的

**Comment by Prinsphield** [comment]
sensitivity可能不同手机会有些差别，这个是一个经验常数。
除了调这个常数之外，如果想要更准的话，可以把`play.py`里`def get_target_position()`下
`pos = multi_scale_search(target, state_cut, 0.4, 15)`里的0.4和15改大一些，当然代价是会慢一些。0.4我觉得大部分情况都应该可以了，你可以单独把15再改大一些，比如20。

**Comment by reaIws** [comment]
谢了
