### ISSUE TITLE
运行一段时间会报如下错误

### ISSUE THREAD

**Issue by duzhiqi** [Prinsphield/Wechat_AutoJump#19]
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resi
ze, file C:\build\master_winpack-bindings-win32-vc14-static\opencv\modules\imgpr
oc\src\resize.cpp, line 4044
Traceback (most recent call last):
  File "play.py", line 169, in <module>
    AI.run()
  File "play.py", line 155, in run
    self.play()
  File "play.py", line 144, in play
    self.target_pos = self.get_target_position(self.state, self.player_pos)
  File "play.py", line 95, in get_target_position
    pos = multi_scale_search(target, state_cut, 0.4, 15)
  File "play.py", line 17, in multi_scale_search
    resized = cv2.resize(screen, (int(W * scale), int(H * scale)))
cv2.error: C:\build\master_winpack-bindings-win32-vc14-static\opencv\modules\img
proc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in f
unction cv::resize

**Comment by Prinsphield** [comment]
可能是没有获取到手机截图，你确定一下手机连接没有问题，并且允许usb调试。
