### ISSUE TITLE
程序报错

### ISSUE THREAD

**Issue by yxyuni** [Prinsphield/Wechat_AutoJump#21]
OpenCV Error: Assertion failed (ssize.area() > 0) in cv::resize, file ..\..\..\..\opencv\modules\imgproc\src\imgwarp.cpp, line 1968
Traceback (most recent call last):
  File "play.py", line 170, in <module>
    AI.run()
  File "play.py", line 156, in run
    self.play()
  File "play.py", line 145, in play
    self.target_pos = self.get_target_position(self.state, self.player_pos)
  File "play.py", line 96, in get_target_position
    pos = multi_scale_search(target, state_cut, 0.4, 15)
  File "play.py", line 18, in multi_scale_search
    resized = cv2.resize(screen, (int(W * scale), int(H * scale)))
cv2.error: ..\..\..\..\opencv\modules\imgproc\src\imgwarp.cpp:1968: error: (-215) ssize.area() > 0 in function cv::resize
这啥情况？

**Comment by Prinsphield** [comment]
应该是没有获取到手机截图。
你在命令行输入`adb devices`看看有没有设备，或者确定一下你的手机是否允许调试

**Comment by yxyuni** [comment]
每次到300多分就死了，可能跑分和机型有关

**Comment by Prinsphield** [comment]
不同机型需要调一下sensitivity或者其他的参数
