### ISSUE TITLE
当目标物体颜色和背景色接近时容易跳不准

### ISSUE THREAD

**Issue by huaifeng1993** [Prinsphield/Wechat_AutoJump#22]
当目标物体颜色和背景色接近时容易跳不准

**Comment by Prinsphield** [comment]
multi-scale search的时候其实用的是灰度图，没有用上颜色的信息，不知道有具体的截图吗？
加上这个`--debug exp`可以打开debug模式

**Comment by twour** [comment]
![state_003_res_h_587_w_461](https://user-images.githubusercontent.com/15318602/34636414-a112e6ee-f2db-11e7-8283-6db060ade198.png)
![state_003_res_h_587_w_461](https://user-images.githubusercontent.com/15318602/34636410-9654abca-f2db-11e7-9174-2b2b87b2c337.png)

**Comment by Prinsphield** [comment]
@twour 你有teamviewer吗，截图给我，我给你调一下？
 
 另外，你是不是改了sleep的时间，小人需要落稳了才行。

**Comment by huaifeng1993** [comment]
可以正常使用，貌似不是颜色问题。多谢
