### ISSUE TITLE
能不能添加一个随机偏离的功能

### ISSUE THREAD

**Issue by simon300000** [Prinsphield/Wechat_AutoJump#25]
我感觉跳的太准会被企鹅发现→_→
我不会Python所以我自己试试

**Comment by Prinsphield** [comment]
这个自己改就好了，我希望代码放出来是最准的版本。

想要随机偏一点很简单，你只要在计算好的`press_time`上加一点随机就好了，`play.py` 119行改成
`press_time = int(press_time + 10 * np.random.random())`
我没有试过，10你可以换成其他的数字调整。

**Comment by simon300000** [comment]
呀，刚刚改完看到你回复了。
我做了一个参数--random
我偏离了distance

**Comment by Prinsphield** [comment]
谢谢你的建议
