### ISSUE TITLE
小米Mix2跳的也不准，是不是分辨率的问题？

### ISSUE THREAD

**Issue by Dike90** [Prinsphield/Wechat_AutoJump#26]
MIX2的分辨率是2160X1080，我得怎么改参数才能跳的准呢。

**Comment by Dike90** [comment]
我想，由于我的屏幕分辨率的比例是2:1的，跟你们16:9的比例不一样，所以导致图像resize后变形，造成识别不准，总是原地跳。我想了个比较简单的解决方案，就是将图片进行裁剪，裁剪成1920*1080的分辨率。然后识别的就还算可以了，--sensitivity 2.2左右。

**Comment by Prinsphield** [comment]
赞自己动手解决问题的，我resize的时候是保持aspect ratio的，长多出来的部分会截掉。
