### ISSUE TITLE
小米5s 总是跳到100左右，跳的距离不够。分辨率1920 * 1080

### ISSUE THREAD

**Issue by showniu** [Prinsphield/Wechat_AutoJump#27]

**Comment by Prinsphield** [comment]
可以试试调大点sensitivity

**Comment by showniu** [comment]
哈哈，秒回呀！我还给调小了，我调大试试！感谢

**Comment by Prinsphield** [comment]
职业操守😂

**Comment by showniu** [comment]
调大之后（2.055、2.065、、、），跳不过30

**Comment by Prinsphield** [comment]
你有teamviewer吗，开着截个图，我给你看看？

**Comment by showniu** [comment]
...... --sensitivity 2.055   这样调的

**Comment by showniu** [comment]
104 678 756
28v3iq

**Comment by Prinsphield** [comment]
小米5s分辨率1920 * 1080， sensitivity 大概为2.22，`play.py`里的96行可以调整为
```
pos = multi_scale_search(target, state_cut, 0.5, 20)
```

**Comment by jirujun** [comment]
sensitivity 取值逻辑或方法，可否说一下，我在iphone 6 plus 默认参数，到500分左右就挂了，iphoneX上无法进行，几步就挂，但是CNN搜索在6plus上是永动，在 iphonex上也是几步就挂，我个人感觉应该是分辨率的事。谢谢。

**Comment by jirujun** [comment]
![state_095_res_h_506_w_606](https://user-images.githubusercontent.com/4016908/34634632-f495685c-f2c0-11e7-9b6b-09bce23d67ec.png)

**Comment by Prinsphield** [comment]
@jirujun 你电脑上有teamviewer吗，打开截个图，我给你看看？

**Comment by jirujun** [comment]
@Prinsphield  高分辨率手机 会有不能运行的情况，如iphone x ,我提交了一个requests ,请审核。

**Comment by jirujun** [comment]
如果你的分辨率高度超过了1280，应该是分辨率的问题，我提交了FIX，官方还没合并，您可以试一下。

**Comment by zhangpeng812** [comment]
为什么我的5s只跑日志,不跳

**Comment by jirujun** [comment]
@zhangpeng812 我预估那您还是配置的事。

**Comment by FreeApe** [comment]
@Prinsphield 分辨率1280x720，采用默认sensitivity ,有时候很准，有时候直接跳过了，总分数还没超过70分。。试了好几次。

**Comment by Prinsphield** [comment]
@FreeApe 你有teamviewer吗，打开截个图，我给你看看？

**Comment by FreeApe** [comment]
556 942 797
w49x5m

**Comment by FrankYing** [comment]
小米5 分辨率1920 * 1080， sensitivity 调整为2.20，play.py里的96行可以调整为
pos = multi_scale_search(target, state_cut, 0.5, 20)

极大概率会跳到最中间，比之前默认以及其他参数效果都要好。

**Comment by Prinsphield** [comment]
想要完美的performance，请使用`nn_play.py`。
