### ISSUE TITLE
Game Over 之后还在点击

### ISSUE THREAD

**Issue by awwwq** [Prinsphield/Wechat_AutoJump#28]
希望可以检测游戏失败
然后提供个参数选择无限重刷或失败则停止

**Comment by Prinsphield** [comment]
明白你的意思，这个好办。

**Comment by awwwq** [comment]
我想请教一个问题
我应该如何在debug的图片上用方框标记出CNN检测出来的区域
就像这个样子
![v2-33903afaae2204eb41e77e9a8a12a804_hd](https://user-images.githubusercontent.com/13381768/34637610-c95716f2-f2f4-11e7-8841-bc1a7978cb98.jpg)

**Comment by pkuanjie** [comment]
目前没有提供这个功能，因为我们没有用到detection，我们用的是regression
