### ISSUE TITLE
大概50几跳之后就不行了

### ISSUE THREAD

**Issue by twour** [Prinsphield/Wechat_AutoJump#30]
默认配置。大概50几跳之后就不行了

![state_053_res_h_589_w_498](https://user-images.githubusercontent.com/15318602/34636618-c1d98bb2-f2e0-11e7-9001-94be0b93f349.png)

**Comment by Prinsphield** [comment]
有teamviewer吗，打开截个图，我给你看看？

**Comment by twour** [comment]
437 182 278
9683

**Comment by Prinsphield** [comment]
不好意思，昨天有点事，你今天需要的话可以再发一次
