### ISSUE TITLE
play.py 报错 AttributeError: 'NoneType' object has no attribute 'shape' 怎么解决

### ISSUE THREAD

**Issue by zhangYanGitHub** [Prinsphield/Wechat_AutoJump#31]
python E:\download\Wechat_AutoJump-master\play.py --phone Android --sensitivity 2.045
报错信息 

/sdcard/1.png: 1 file pulled. 1.4 MB/s (59991 bytes in 0.041s)
Traceback (most recent call last):
  File "E:\download\Wechat_AutoJump-master\play.py", line 172, in <module>
    AI.run()
  File "E:\download\Wechat_AutoJump-master\play.py", line 157, in run
    self.play()
  File "E:\download\Wechat_AutoJump-master\play.py", line 137, in play
    self.player_pos = self.get_player_position(self.state)
  File "E:\download\Wechat_AutoJump-master\play.py", line 84, in get_player_position
    pos = multi_scale_search(self.player, state, 0.3, 10)
  File "E:\download\Wechat_AutoJump-master\play.py", line 14, in multi_scale_search
    h, w = pivot.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by importer** [comment]
我也遇到同样的问题

**Comment by zhangYanGitHub** [comment]
大神有没有win10  cuDNN v6.0的包 官网维护下不了

**Comment by Prinsphield** [comment]
NoneType应该是没有获取到截图，你最好进入`play.py`所在的目录下`python play.py`.

我不用win10，只有linux的😂

**Comment by zhangYanGitHub** [comment]
@Prinsphield 好的 我试试

**Comment by zhangYanGitHub** [comment]
@Prinsphield 已经好了 不过每次跳的位置有点偏

**Comment by zaleCao** [comment]
同样的问题，在目录下python play.py 也是一样，我是一加5T

**Comment by zaleCao** [comment]
是我的path问题，解决了

**Comment by yongcong1415** [comment]
baidu里面的data文件一定要下载下来吗？我是win7 64+android，运行也是你这个一模一样的问题，我只安装了py3.6+opencv+numpy,谢谢！tensorflow没安装。

**Comment by FrankYing** [comment]
我的一开始也是这样，是Android的adb没有设置好的原因，你可以试下adb命令是否正常。另，手机也要设置成开发者模式。
