### ISSUE TITLE
sensitivity取2.045s是调参调出来的吗~~

### ISSUE THREAD

**Issue by coolKeen** [Prinsphield/Wechat_AutoJump#36]

**Comment by coolKeen** [comment]
是，当我没问:）

**Comment by wqw547243068** [comment]
有快速的调参方法吗？不同实际的分辨率不同，非得自己人肉调参吗

**Comment by Prinsphield** [comment]
@wqw547243068 一般就是人肉调，而且参数也不多，不就一个sensitivity嘛😂，你可以开debug模式调参，运行命令的时候加上`--debug exp`可以看到结果图

**Comment by junhe102** [comment]
当目标图在屏幕很远的地方，只有一半在可视区，target_pos查找有问题。

**Comment by Prinsphield** [comment]
是跑的`nn_play.py`吗？

**Comment by junhe102** [comment]
@Prinsphield 不是的，是直接play.py，nn_play本本跑不起来

**Comment by Prinsphield** [comment]
区域是根据小人的位置对称过去的，如果找错一般是分辨率不一致，匹配不准。

`nn_play.py`cpu也能跑，而且不慢。

**Comment by junhe102** [comment]
OK，果然，nn_play.py可以跑，而且更快，但是nn_play.py 的fine训练模型目录名有点问题，没看仔细。
