### ISSUE TITLE
小米18:9的屏，结果不太准啊，只有22分

### ISSUE THREAD

**Issue by hurricanedjp** [Prinsphield/Wechat_AutoJump#39]

**Comment by Prinsphield** [comment]
有teamviewer吗，打开截个图，我帮你看看？

**Comment by hurricanedjp** [comment]
有teamviewer，额，要怎么把截图给你看？ 另外我在ubuntu上跑的，先跑的play.py,最多只有22，后来下了模型，跑的nn_play.py,最多只有66，大部分还是二十多，从最开始就不是跳到最中心的位置

**Comment by Prinsphield** [comment]
你打开teamviewer，把id和passwd告诉我，我远程给你看看

**Comment by hurricanedjp** [comment]
id:702 791 318
passwd: sg472x

另外，我刚刚试了华为的手机也是18比9的，那个手机可以
