### ISSUE TITLE
选择安卓参数为什么不对？

### ISSUE THREAD

**Issue by shen-lan** [Prinsphield/Wechat_AutoJump#4]
$ python play.py --Android --sensitivity 2.045
usage: play.py [-h] [--phone {Android,IOS}] [--sensitivity SENSITIVITY]
               [--resource RESOURCE] [--debug DEBUG]
play.py: error: unrecognized arguments: --Android

**Comment by Prinsphield** [comment]
`python play.py --phone Android --sensitivity 2.045`
