### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by carolcoral** [Prinsphield/Wechat_AutoJump#40]
当我运行时出现以下错误提示：
Traceback (most recent call last):
  File "/Users/carol/Downloads/Wechat_AutoJump-master/play.py", line 8, in <module>
    import cv2
ImportError: No module named cv2
谢谢！
机型：华为荣耀9
系统：安卓

**Comment by Prinsphield** [comment]
请安装opencv3

**Comment by carolcoral** [comment]
谢谢，一发现这个问题，想请问下必须要安装 andrioid studio 才能使用 adb 命令工具吗，因为我 mac 系统没有找到合适的仅安装 adb 命令行工具的说明，谢谢

**Comment by Prinsphield** [comment]
https://stackoverflow.com/questions/31374085/installing-adb-on-mac-os-x
