### ISSUE TITLE
关于base.large/larger/small

### ISSUE THREAD

**Issue by jalllychun** [Prinsphield/Wechat_AutoJump#42]
请问cnn_coarse_to_fine/config里面的几个网络，large，larger 和small是指什么（网络大小还是图片），要全部训练还是训练其中一个就好了？

**Comment by Prinsphield** [comment]
large是训练coarse的网络，fine是训练fine的网络，其他两个应该是之前训练留下的

**Comment by jalllychun** [comment]
@Prinsphield 谢谢
