### ISSUE TITLE
非标分辨率怎么重新训练模型

### ISSUE THREAD

**Issue by RightFS** [Prinsphield/Wechat_AutoJump#45]
不用GPU加速的话大概多长时间，手机是2960x1440的屏，倒是可以降至1480x720.
能讲一下步骤嘛，或者给几个入门学习的链接。
作为搞驱动的码农，对机器学习有兴趣但是似乎没人交流真玩不转。

**Comment by Prinsphield** [comment]
知乎里写了是怎么训练的 https://zhuanlan.zhihu.com/p/32636329
不用GPU训模型还是不要考虑了，只用cpu跑训好的模型还是可以的。
不同分辨率本质上没有什么区别，只是那么高的分辨率也没有必要，可以缩小以后喂给网络，还能减少模型大小。

**Comment by RightFS** [comment]
谢谢，公司这破iMac配置太渣了，真是白瞎这么多钱，明天带自己机器来公司试试。

**Comment by zkailinzhang** [comment]
@Prinsphield 不用GPU训模型还是不要考虑了，只用cpu跑训好的模型还是可以的。..但是现在我的在play.py下跑的要比nn_play下好,,但是都不超过200,,,现在我是要自己训练模型吗,但我只有cpu的,,,gpu没有啊啊,,cpu训练一般多长时间
