### ISSUE TITLE
About show 

### ISSUE THREAD

**Issue by Junjun7** [Prinsphield/Wechat_AutoJump#46]
前辈，我想在跑训练数据的时候看下opencv的分析过程，如何实现呢。打扰您了。

**Comment by Prinsphield** [comment]
没听懂？
 
你是想看inference的时候算法给出的具体位置是吗？

**Comment by pkuanjie** [comment]
跑训练数据是什么意思

**Comment by Junjun7** [comment]
@Prinsphield  是的。就是识别出的位置。给您添麻烦了

**Comment by Junjun7** [comment]
@Prinsphield  是的。就是识别出的位置。给您添麻烦了

**Comment by Junjun7** [comment]
@Richard-An 就是用的resource里的数据是下载下来的train数据。。。可能表达有点不清晰。。。

**Comment by Prinsphield** [comment]
@Junjun7 可以在运行的时候加上`--debug exp`，这样出现一个`exp`文件夹，记录识别的位置。

**Comment by Junjun7** [comment]
@Prinsphield 好的，感谢您指点。贵安！
