### ISSUE TITLE
报错 AttributeError: 'module' object has no attribute 'connectedComponents'

### ISSUE THREAD

**Issue by laobohou** [Prinsphield/Wechat_AutoJump#52]
python2.7，win7
adb是从网上下得的adb（http://www.skycn.net/soft/appid/24272.html）
opencv应该也正确安装，并在调试中正确显示图片。

在运行python play.py --phone Android --sensitivity 2.045时，结果如下：
C:\Users\donglan01\Desktop\tiaoyitiao\Wechat_AutoJump-master>python play.py --phone Android --sensitivity 2.045
2289 KB/s (42206 bytes in 0.018s)
Traceback (most recent call last):
  File "play.py", line 175, in <module>
    AI.run()
  File "play.py", line 160, in run
    self.play()
  File "play.py", line 146, in play
    self.target_pos = self.get_target_position_fast(self.state, self.player_pos)
  File "play.py", line 111, in get_target_position_fast
    b1, b2 = cv2.connectedComponents(m)
AttributeError: 'module' object has no attribute 'connectedComponents'

**Comment by Prinsphield** [comment]
请安装opencv 3

**Comment by laobohou** [comment]
不好意思问了那么低级的问题，我更正后opencv没问题了（版本3.4.0.12）
然后还是有报错，看起来像cv的问题
C:\Users\donglan01\Desktop\tiaoyitiao\Wechat_AutoJump-master>python play.py --phone Android --sensitivity 2.045
1666 KB/s (3412 bytes in 0.002s)
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\projects
\opencv-python\opencv\modules\imgproc\src\resize.cpp, line 4044
Traceback (most recent call last):
  File "play.py", line 175, in <module>
    AI.run()
  File "play.py", line 160, in run
    self.play()
  File "play.py", line 149, in play
    self.target_pos = self.get_target_position(self.state, self.player_pos)
  File "play.py", line 100, in get_target_position
    pos = multi_scale_search(target, state_cut, 0.4, 15)
  File "play.py", line 18, in multi_scale_search
    resized = cv2.resize(screen, (int(W * scale), int(H * scale)))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize
.width > 0 && ssize.height > 0 in function cv::resize
似乎网上说是和截的图片名字有关，麻烦您看看。
很感兴趣你的项目，非常感谢你的付出！

**Comment by Prinsphield** [comment]
有teamviewer吗，打开告诉我id和passwd，我给你看看

**Comment by yangkr** [comment]
好的，谢谢。账号709233373@qq.com 密码1qaz2wsx
我到0点半前都在

**Comment by Prinsphield** [comment]
id是一个9位数字

**Comment by yangkr** [comment]
465329020

**Comment by laobohou** [comment]
恩，以为是直接连接

**Comment by Prinsphield** [comment]
你没开啊

**Comment by yangkr** [comment]
162 407 553

**Comment by Prinsphield** [comment]
密码？

**Comment by laobohou** [comment]
之前那个错了。。抱歉

**Comment by yangkr** [comment]
123456，好像是。但我这显示没有密码

**Comment by yangkr** [comment]
我之前的意思是，你用账号709233373@qq.com登录，对应的密码是1qaz2wsx

**Comment by Prinsphield** [comment]
我还想试试

**Comment by laobohou** [comment]
恩，连接吧

**Comment by Prinsphield** [comment]
再告诉一下id和passwd

**Comment by yangkr** [comment]
709233373@qq.com 1qaz2wsx
ID那个是162 407 553，密码好像是123456

**Comment by laobohou** [comment]
感谢作者的付出和帮助，检查发现，过低版本的Android手机可能没有press time参数，不能实现触屏操作。所以需要比较高版本的Android手机

**Comment by Prinsphield** [comment]
前面报的错貌似是你操作的问题😂

**Comment by laobohou** [comment]
啊，对，adb建议用官网的。。我好像是从某个国内网站下的
