### ISSUE TITLE
读不懂训练文件的说明

### ISSUE THREAD

**Issue by kingshiplet** [Prinsphield/Wechat_AutoJump#53]
如果你想从头自己训练： 下载好数据到任意目录下，然后修改cnn_coarse_to_fine/data_provider目录下所有文件的self.data_dir路径。
1这句话读不懂是吧解压后的自己训练的文件改名为self.data_dir吗？
2并放在cnn_coarse_to_fine/data_provider目录下？
3如果模型文件放到相应文件夹下和训练文件放到也放到说明的目录下会冲突吗？
系统是训练还是按照模型文件来执行？还是只能放模型和训练的一种来跑？

**Comment by Prinsphield** [comment]
是说在`cnn_coarse_to_fine/data_provider`目录下所有文件里`self.data_dir`指定为你解压的路径。
