### ISSUE TITLE
如果只用了你们的这个train_log文件

### ISSUE THREAD

**Issue by ShilangChen1011** [Prinsphield/Wechat_AutoJump#54]
只用了你们训练的数据，没有下载data，我自己在跳的过程中还会还会进行训练吗，我跳的越多是否会增加我提高分数的可能性。

**Comment by Prinsphield** [comment]
不会，那个是已经训练好的模型文件。

**Comment by soapmancn** [comment]
@Prinrp 为什么用训练好的模型跳不到几步就死了

**Comment by Prinsphield** [comment]
@soap-man 可能需要调一下sensitivity

**Comment by ruicky** [comment]
@Prinsphield  sensitivity 调整 有大概说明吗？
iPhone 7 plus sensitivity 给多大比较合适？

**Comment by Prinsphield** [comment]
这个得自己看着调，我也没有那么多种手机可以给你们都一一试一下
运行代码后面加上  `--debug exp`可以开debug模式

**Comment by Prinsphield** [comment]
@ruicky 如果需要的话，留一下teamviewer的id和passwd，我给你看看
