### ISSUE TITLE
paly.py文件中没有用到TesorFlow，是否说明nn_play.py的效果更好

### ISSUE THREAD

**Issue by ShilangChen1011** [Prinsphield/Wechat_AutoJump#55]
paly.py文件中没有用到TesorFlow，是否说明nn_play.py的效果更好

**Comment by Prinsphield** [comment]
和tf没有关系，`play.py`没有上深度学习，但是在我个人的手机上已经是永动机了，拿来跑的数据可以训练cnn模型。

cnn模型的好处是对不同分辨率兼容性会好一些，因为多尺度匹配对其他的非16：9分辨率可能效果会不太理想，因为resource里的素材都是16：9手机上的，在其他的比例下可能不是很适应。

**Comment by ShilangChen1011** [comment]
不是特别懂你说的，CNN不就是深度学习的一种吗，难道是说play.py没有用到cnn？就是说如果不是16:9的手机最好不用play.PY，而需要自己进行训练，同时需要用到tf？

**Comment by Prinsphield** [comment]
`play.py`用的是multiscale search + fast search，`nn_play.py`用的是cnn search + fast search。

在16:9的数据上训好的cnn在非16:9下也能work，不需要重新训练，这是cnn的方法的优势所在。

**Comment by ShilangChen1011** [comment]
![image](https://user-images.githubusercontent.com/28330374/34685484-72053492-f4e3-11e7-8b18-5077e17ead7f.png)
红圈出来的是什么意思呀

**Comment by ShilangChen1011** [comment]
![image](https://user-images.githubusercontent.com/28330374/34685703-36f7550a-f4e4-11e7-9e6c-f8da2a9c3f21.png)
请问数据的这些文件夹有什么含义，是每次进行训练得到的，会每次增加个文件夹吗，但是我这里没有。

**Comment by Prinsphield** [comment]
红圈是表示你给手机的指令。

你不开debug模式就没有这些文件夹

**Comment by ShilangChen1011** [comment]
我就是想问那后面的数字代表啥  ，是像素吗

**Comment by ShilangChen1011** [comment]
怎么关闭debug模式，是python的debug模式吗

**Comment by Prinsphield** [comment]
不加`--debug xxx`就可以

**Comment by ShilangChen1011** [comment]
![Uploading image.png…]()

**Comment by ShilangChen1011** [comment]
我没加哈，是你那边下载的，可以删掉这些吗，数据量有点大。

**Comment by Prinsphield** [comment]
`data/exp_xx`是训练数据，如果你不自己训练可以不需要
