### ISSUE TITLE
训练CNN模型疑问

### ISSUE THREAD

**Issue by ruicky** [Prinsphield/Wechat_AutoJump#58]
> 你好，对于训练模型我是新手，但是根据文档提示，做出以下操作:

## 训练CNN模型

1. 将下载`data`文件解压到本项目中
2. 修改`Wechat_AutoJump/data_provider`文件夹下
    + `jump_data_fine.py`文件的 第7行 `self.data_dir = '/home/anjie/projects/we_jump/data'` 为 `self.data_dir = '/Users/ruicky/Documents/github/Wechat_AutoJump/data'` (**注:**后面的路径改为自己的绝对路径)
    + `jump_data.py`文件的 第7行 `self.data_dir = '/home/anjie/projects/we_jump/data'` 为 `self.data_dir = '/Users/ruicky/Documents/github/Wechat_AutoJump/data'` (**注:**后面的路径改为自己的绝对路径)
3. 猜测，根据jumo_data_fine.py中的`fine`用的是fine模型，故：
    + 修改`Wechat_AutoJump/cnn_coarse_to_fine/config/base.fine/train.py` 第2行`sys.path.append('/home/anjie/projects/we_jump/')` 为  `sys.path.append('/Users/ruicky/Documents/github/Wechat_AutoJump/')`
    + `cd cnn_coarse_to_fine/config/base.fine`
    + `python3 train.py -g 0`

但是运行以后报错如下:

```shell
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from data_provider.jump_data_fine import JumpData
ModuleNotFoundError: No module named 'data_provider'
```    

希望能帮忙解答以下。

**Comment by Prinsphield** [comment]
你把`train.py`第二行的路径改成到`/path/to/Wechat_AutoJump/cnn_coarse_to_fine/`试试

**Comment by Prinsphield** [comment]
我重新修改了，你直接git pull一下

**Comment by ruicky** [comment]
@Prinsphield  OK,修改完后，可以运行了。
问一下,运行后显示以下的，是正常的么？还有大概训练得多长时间？
```shell
python3 train.py -g 0
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
2018-01-09 10:12:31.193478: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
```

**Comment by Prinsphield** [comment]
正常。有gpu的话，10个小时吧

**Comment by ruicky** [comment]
@Prinsphield  好的，还有个疑问，就是 我看是同样的配置文件，自己跑的模型 跟你最后跑成功的 有什么区别么？

**Comment by Prinsphield** [comment]
没区别

**Comment by zkailinzhang** [comment]
@ruicky @Prinsphield 请教下,自己训练模型是用自己调试生成的图片,还是要用楼主给的数据啊,,,,利用这些数据去训练模型也就是加快 识别目标坐标,,,是不是,,,,与那个参数没有关系,参数仍然要自己手动调,,是吧,,
