### ISSUE TITLE
安卓手机可以用nnplay吗？怎么用？还有我的小米5c，5.15英寸16:9,1980*1080怎么调参数？

### ISSUE THREAD

**Issue by TjuJiang** [Prinsphield/Wechat_AutoJump#59]
安卓手机可以用nnplay吗？怎么用？还有我的小米5c，5.15英寸16:9,1980*1080怎么调参数？

**Comment by Prinsphield** [comment]
可以`python nn_play.py --phone Android --sensitivity 2.045`

**Comment by aqnaruto** [comment]
请教一下 需要装一些依赖吗 
![image](https://user-images.githubusercontent.com/9067159/34725389-b9fce1c0-f58b-11e7-89f6-d62acd9d9074.png)

**Comment by Prinsphield** [comment]
安装numpy
