### ISSUE TITLE
android 小米5S PLUS 分辨率1920*1080跳的不准

### ISSUE THREAD

**Issue by XINDZ** [Prinsphield/Wechat_AutoJump#6]
android 小米5S PLUS 分辨率1920*1080跳的不准很少落地中心点,跳到50多久gameover了

**Comment by XINDZ** [comment]
第二次跳到100+挂掉了

**Comment by Prinsphield** [comment]
需要我帮你调试吗？请打开teamviewer，截个图给我

**Comment by XINDZ** [comment]
OK 我又跑了几次最高121
ID 436 591 827
PWD7752

**Comment by XINDZ** [comment]
十分感谢作者 帮吗远程调试了系数,并提供了调试的方法
我的机型是小米5S PLUS的系数为2.22左右
