### ISSUE TITLE
play.py运行出错

### ISSUE THREAD

**Issue by Qian-z** [Prinsphield/Wechat_AutoJump#60]
机型：小米5，运行代码后出现如下错误
/sdcard/1.png: 1 file pulled. 8.2 MB/s (135197 bytes in 0.016s)
multiscale-search, step: 0004
adb shell input swipe 245 800 245 800 682
/sdcard/1.png: 1 file pulled. 8.4 MB/s (138446 bytes in 0.016s)
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\projects\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp, line 3483
Traceback (most recent call last):
  File "play.py", line 146, in play
    self.target_pos = self.get_target_position_fast(self.state, self.player_pos)
  File "play.py", line 117, in get_target_position_fast
    h, w = int(r_x.mean()), int(r_y.mean())
UnboundLocalError: local variable 'r_x' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "play.py", line 175, in <module>
    AI.run()
  File "play.py", line 160, in run
    self.play()
  File "play.py", line 149, in play
    self.target_pos = self.get_target_position(self.state, self.player_pos)
  File "play.py", line 100, in get_target_position
    pos = multi_scale_search(target, state_cut, 0.4, 15)
  File "play.py", line 18, in multi_scale_search
    resized = cv2.resize(screen, (int(W * scale), int(H * scale)))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:3483: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

**Comment by Prinsphield** [comment]
没有获取到截图，请到项目目录下跑程序。
