### ISSUE TITLE
多谢大牛大牛提供的全部代码及详细的运行说明

### ISSUE THREAD

**Issue by bonebo** [Prinsphield/Wechat_AutoJump#62]
首先感谢大牛提供的全部代码及详细的运行说明。我第一次玩Python和TensorFlow，折腾了3天了。
安装配置环境出了一堆问题，最终都解决了（此处省略一万字）。现在直接运行现成的play.py没问题。跑了几百分。
后来在自己重新训练模型时，也是出了无数的问题，直到最后出现的问题始终解决不了，就是tqdm找不到，我才注册了账号，准备求助了。
就在我发这个问题的时候，才试着单独装一下tqdm，然后就Ok了。正在训练了。
然后问题贴就变成了感谢贴了。

**Comment by Prinsphield** [comment]
😂😂😂

**Comment by bonebo** [comment]
有没有什么博客，微信公众号什么的，想继续跟进大牛的最新动向。

**Comment by Prinsphield** [comment]
https://prinsphield.github.io/year-archive/
公众号没有

**Comment by aqnaruto** [comment]
你把之前的问题都删了 对我们不是没有用了 
  原本我不是写python的 我现在还在下pip

**Comment by bonebo** [comment]
我的问题纯小白问题，不提也罢。
