### ISSUE TITLE
电脑Mac，手机Android，'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by MJeremy2017** [Prinsphield/Wechat_AutoJump#63]
我不知道操作流程对不对
我git clone项目到电脑中，然后也装了adb tools，打开了adb tools，
然后手机接入电脑。cd到项目所在目录下，打开游戏，然后运行python play.py --phone Android --sensitivity 2.045
结果报错：AttributeError: 'NoneType' object has no attribute 'shape'
我尝试了python nn_play.py --phone  Android--sensitivity 2.045
仍然报错Not found: resource/train_logs_coarse; No such file or directory
能帮出解释吗，谢谢！

**Comment by Prinsphield** [comment]
你跑的是`nn_play.py`吧，需要下载训好的模型

跑`play.py`中间没有获取到截图，你有teamviewer吗，打开给我截个图，我远程给你看看？

**Comment by ShilangChen1011** [comment]
跑nn_paly.py不是用cnn重新进行训练吗，还需要下载训练好的？

**Comment by Prinsphield** [comment]
不用重新训练，只要下载训练好的

**Comment by ShilangChen1011** [comment]
那我要自己训练，如何操作呢。

**Comment by ShilangChen1011** [comment]
要下载哪些，和运行哪个？

**Comment by Prinsphield** [comment]
请仔细阅读https://github.com/Prinsphield/Wechat_AutoJump/blob/master/readme_cn.md

**Comment by MJeremy2017** [comment]
@Prinsphield 不好意思我teamviewer用不了， 您方便加微信吗？15815589628
我看您的解释中android是不是不需要下载训练数据啊
或者问题是  手机接入电脑后不需要任何其它操作吗？

**Comment by Prinsphield** [comment]
@MJeremy2017 训练数据不需要，如果要跑nn_play.py，需要训练好的模型文件
