### ISSUE TITLE
程序出错

### ISSUE THREAD

**Issue by checkjiajiaup** [Prinsphield/Wechat_AutoJump#67]
C:\Users\Administrator\Desktop\wechatjump\Wechat_AutoJump-master>python play.py
--phone Android --sensitivity 2.045
2734 KB/s (27997 bytes in 0.010s)
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resi
ze, file C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp, line 4
044
Traceback (most recent call last):
  File "play.py", line 146, in play
    self.target_pos = self.get_target_position_fast(self.state, self.player_pos)

  File "play.py", line 117, in get_target_position_fast
    h, w = int(r_x.mean()), int(r_y.mean())
UnboundLocalError: local variable 'r_x' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "play.py", line 175, in <module>
    AI.run()
  File "play.py", line 160, in run
    self.play()
  File "play.py", line 149, in play
    self.target_pos = self.get_target_position(self.state, self.player_pos)
  File "play.py", line 100, in get_target_position
    pos = multi_scale_search(target, state_cut, 0.4, 15)
  File "play.py", line 18, in multi_scale_search
    resized = cv2.resize(screen, (int(W * scale), int(H * scale)))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044:
 error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

大佬  这个是什么问题呀？？

**Comment by Prinsphield** [comment]
没有读取到手机截图，你看看`adb devices`有没有设备。

**Comment by checkjiajiaup** [comment]
有设备 但我调试的是安卓模拟器 用模拟器再跑微信跳一跳  这个会不会对程序有影响呢？
  @Prinsphield

**Comment by Prinsphield** [comment]
应该没问题，但是报错是没有读取到模拟器的截图，你再找找是什么原因

**Comment by checkjiajiaup** [comment]
可以了 模拟器模式问题 设置的平板模式 改成手机就可以了  感谢大佬 @Prinsphield
