### ISSUE TITLE
Wrong target position

### ISSUE THREAD

**Issue by ustcjerry** [Prinsphield/Wechat_AutoJump#68]
In the file `play.py` line 95:
`sym_br = np.array([min(sym_center[0] + self.bb_size[0]//2, player_pos[0]), min(sym_center[0] + self.bb_size[1]//2, 720)])`

the y coordinate should be:
`min(sym_center[1] + self.bb_size[1]//2, 720)`

**Comment by Prinsphield** [comment]
thank you very much
