### ISSUE TITLE
运行成功了，写个针对没用过python的小白的小结吧。

### ISSUE THREAD

**Issue by aqnaruto** [Prinsphield/Wechat_AutoJump#69]
项目有依赖包，因此确认 环境装的python有pip包管理器。
其中用到了numpy, cv2。
依次 pip install numpy
 pip install opencv-python

nn_play 需pip3 install --upgrade tensorflow-gpu

结论，我用的play.py的实际测试不理想，一是跳一步间隔太久 2是跑不了多高分，昨天用知乎上 神奇的战士  跑到470多分，
这个跑到百来分就挂了。 
暂时情况是这样，继续研究ing
  
---
更新 因为在安卓上不理想，用mac+肾7跑。
mac安装cv2
参考了https://www.cnblogs.com/brucemengbm/p/6882063.html

**Comment by Prinsphield** [comment]
你的分辨率是多少，可以试着调一下sensitivity.

如果觉得还不满意，请跑nn_play.py

**Comment by aqnaruto** [comment]
谢谢 720*1280，红米4a，我试试
……
更新 重新clone了 你一小时前的版本，十几分到一百分内就会挂。玩的还是 play.py 等下再试试nn_play

**Comment by Prinsphield** [comment]
有teamviewer吗，告诉我id和passwd，我给你看看？

**Comment by aqnaruto** [comment]
409 053 597 密码 4472

**Comment by aqnaruto** [comment]
静距离感受大神 谢谢。我去试试

**Comment by Prinsphield** [comment]
`play.py`在我个人手机上完全无压力，但是还是在很多手机上会不太行，这种情况还是用`nn_play.py`吧

**Comment by aqnaruto** [comment]
好的 感谢 ，第一次近距离感受到了python+ai的炫酷。
