### ISSUE TITLE
小米6不跳

### ISSUE THREAD

**Issue by WindBruce** [Prinsphield/Wechat_AutoJump#7]
能运行，但一直不跳，操控不了。

**Comment by WindBruce** [comment]
小米6安卓8.0

**Comment by Prinsphield** [comment]
打开teamviewer，给我截个图，我远程帮你看看

**Comment by WindBruce** [comment]
![default](https://user-images.githubusercontent.com/30388825/34552269-70bdc9f4-f15b-11e7-9ee0-bc0effd70761.png)
一直这样截图计算，但无反应。

**Comment by Prinsphield** [comment]
你ctrl+C，重新来试试

**Comment by oi-io** [comment]
MIUI需要打开安全设置(模拟点击)

**Comment by WindBruce** [comment]
打开模拟点击成功了

**Comment by zhangpeng812** [comment]
模拟点击怎么打开?5s找不到

**Comment by hurricanedjp** [comment]
是指的开发者模式里usb安全设置吧

**Comment by GaoLoo** [comment]
2.193 能跳1K+

**Comment by hurricanedjp** [comment]
Fixes #7
