### ISSUE TITLE
红米note4X 1920*1080分辨率的用nn_play.py还是不行，二三十分就挂了

### ISSUE THREAD

**Issue by littlekuo** [Prinsphield/Wechat_AutoJump#75]

**Comment by littlekuo** [comment]
![state_008_res_h_497_w_318](https://user-images.githubusercontent.com/19264283/34810244-076d0760-f6d5-11e7-99a2-e8624264749a.png)

**Comment by littlekuo** [comment]
会出现上面那种红点不在方块中心的情况

**Comment by cherryxyz** [comment]
我也出现差不多这种情况

**Comment by Prinsphield** [comment]
有teamviewer吗，打开，告诉我id和passwd，我看一眼

**Comment by littlekuo** [comment]
调整了一下sensitivity，现在能跑200多了，但还是会出现红点不在正中心的情况，这是误差范围内的吗？

**Comment by Prinsphield** [comment]
@Mhahaha 你有teamviewer吗，打开，告诉我id和passwd，我给你弄一下

**Comment by littlekuo** [comment]
498 679 254      
7768
