### ISSUE TITLE
iPhone 7 Plus 机型下 sensitivity 系数如何调整？

### ISSUE THREAD

**Issue by ruicky** [Prinsphield/Wechat_AutoJump#77]
平台：IOS，
型号：iPhone 7 Plus
问题：使用 `--sensitivity 2.045` 在该机型上只能到30多分就失败了，最高一次是118，能否告知，sensitivity 参数的合理值是多少？
补充： 使用 `python nn_play.py --phone IOS --sensitivity 2.045`运行。

**Comment by Prinsphield** [comment]
亲，我没有各种各样的手机，无法一一给大家试出最优参数。只能告诉你方法，自己调试。

运行的时候加上`--debug exp_01`，会得到一个`exp_01`文件夹，里面有检测的结果，你看相邻两次跳跃的结果，每次跳跃的位置是否在检测出的位置，如果不够，就把`sensitivity`调大，反之调小。

**Comment by ruicky** [comment]
@Prinsphield 按照你提供的方法测试，发现在过程中，这种图 识别错误，有解决的办法不？
![error](http://ww3.sinaimg.cn/large/0060lm7Tly1fndkotvm2gj30k00zk7ab.jpg)

**Comment by Prinsphield** [comment]
不要改sleep的时间
