### ISSUE TITLE
谢谢代码，亲测小米max2,1920x1080分辨率，play.py脚本，失误率极低，10000+完全没问题，处理了一下非线性问题

### ISSUE THREAD

**Issue by ysagabong** [Prinsphield/Wechat_AutoJump#78]
`        distance = np.linalg.norm(player_pos - target_pos)`
`        print distance`
`        press_time = distance * self.sensitivity`
`        print press_time`
`        press_time = int(np.rint(press_time))`
`        if press_time > 1000 :`
`            press_time=press_time-10-int((press_time-1000)/4)`
`        if distance < 320 :`
`            press_time=press_time+10+int((320-distance)/5)`
 `       print press_time`

--sensitivity 2.192

**Comment by ysagabong** [comment]
![state](https://user-images.githubusercontent.com/35328219/34816397-c0e45e0e-f6ef-11e7-9a44-fc764ac70653.png)

**Comment by Prinsphield** [comment]
谢谢建议，我试一下你的修改

**Comment by Prinsphield** [comment]
你是处理了过近或者过远的情况，那几个参数可能在你的手机上适用，我这反而不好，不过我倒是可以把press_time取整改为取整至最近的int。

**Comment by ysagabong** [comment]
嗯，看来是手机问题。不同手机需要不一样的调整

**Comment by cherryxyz** [comment]
同为小米max2   
用了这个确实应该可以做到一直跳下去了。每跳一步加28分。。。
话说对于腾讯作弊处理，有没有什么高见。

**Comment by ysagabong** [comment]
@Prinsphield 脚本作者的本意并不是让你去刷排行榜，没有意义，而是让更多的人去感受程序的乐趣。游戏是给人玩的，不同人有不同的玩法，所以我们有我们的opencv图像处理的玩法。腾讯也知道我们没有触碰游戏内核，没有修改游戏内存，所以只是做了删榜处理，这一点，还是很道德的。

**Comment by ysagabong** [comment]
对于1920x1080（16:9）分辨率的手机，太远太近的情况出现按压时间与距离的非线性问题，应该是作者 @Prinsphield 的脚本是1280x720（16:9）的问题。所以，1280x720手机用作者默认参数应该是完全没问题的。

**Comment by cherryxyz** [comment]
我哪里有说我要去刷排行榜了。。。。我只是想知道官方判定我们作弊的原理好不好

**Comment by ysagabong** [comment]
可以这样说，如果腾讯没有检测我们游戏时是否处于adb连接状态，他们不会知道你用没用脚本。官方只能删高分榜

**Comment by kingaza** [comment]
赞。@yangshenbang 是怎么调出这些参数的啊
