### ISSUE TITLE
ZUK Z2（1920*1280）调到1w分还是出错了

### ISSUE THREAD

**Issue by VistaQvQ** [Prinsphield/Wechat_AutoJump#79]
具体情况如图所示

![state_606_res_h_585_w_485](https://user-images.githubusercontent.com/23132799/34866149-7aab40d4-f7b6-11e7-80b6-7123a7514cc8.png)

**Comment by Prinsphield** [comment]
你用的play还是nn_play?

**Comment by VistaQvQ** [comment]
我用的play

**Comment by Prinsphield** [comment]
在其他分辨率的手机上匹配会存在问题
