### ISSUE TITLE
求助帖：没上过100分

### ISSUE THREAD

**Issue by TyGuo** [Prinsphield/Wechat_AutoJump#83]
使用nn_play，在iphone6sp 上没上过100分；
总会出现奇妙的小跳，不知道是什么方面的问题。
一般就二三十分，下载了预训练的模型。

**Comment by Prinsphield** [comment]
可能需要调一下sensitivity。

有teamviewer吗，打开告诉我id和passwd，我帮你看看

**Comment by TyGuo** [comment]
504 293 629
8jxk13
谢谢了

**Comment by Prinsphield** [comment]
好像你没有打开
