### ISSUE TITLE
程序跑的起来，但很快死了，手机型号mi max2 分辨率1920*1080

### ISSUE THREAD

**Issue by xiongxiao91** [Prinsphield/Wechat_AutoJump#87]
你好大腿，程序跑起来了，用的也是提供的训练数据，但是经常跳不过10分，最多一次才43分，请问大腿会不会和手机有关啊，我的手机型号mi max2 分辨率1920*1080，可以挽救吗？

**Comment by Prinsphield** [comment]
应该需要调整一下`sensitivity`，你试试2.22看看
