### ISSUE TITLE
请问分数高不了是什么原因

### ISSUE THREAD

**Issue by Fykex** [Prinsphield/Wechat_AutoJump#91]
跳了两小时，最高才100多分，用的play.py

**Comment by Fykex** [comment]
mac+iphone7

**Comment by Prinsphield** [comment]
请用nn_play.py

**Comment by Prinsphield** [comment]
如果没弄好，请打开teamviewer，把id和passwd告诉我，我给你看看？

**Comment by ChangzeYan** [comment]
我用的nn_play.py，为什么分数最高也才100？

**Comment by Prinsphield** [comment]
@Yahtz 可能sensitivity没有调对

**Comment by Fykex** [comment]
@Prinsphield 谢谢，后面又能到300以上了

**Comment by Fykex** [comment]
@Prinsphield 分数被清了，为什么会被发现的呢，还能精准的回滚到我手动玩的分数

**Comment by Prinsphield** [comment]
@Fykex 要上10000才能说明弄好了😂😂

**Comment by zkailinzhang** [comment]
上1000只调系数不行吧,是不是都要自己训练啊??

**Comment by Prinsphield** [comment]
@zkl99999 应该不用

**Comment by Fykex** [comment]
@Prinsphield 之前nn_play运行不了 更新了TensorFlow可以了，准的不行😂😂
