### ISSUE TITLE
感觉参数没调好呢,  nn和play 都是跑到6.700就掉地上了,,,,,

### ISSUE THREAD

**Issue by zkailinzhang** [Prinsphield/Wechat_AutoJump#93]
小米5s,,,2.1948,,连跳最多20次就不会在连调了,尤其碰到,目标是白色面的 就停止连跳,
像我这种是不是自己训练模型也不行,,训练应该是楼主给的数据是吧,不是自己debug生存的,,,但训练出的cnn也就能提高目标识别率是吧,参数还是要自己调?????这个参数能否也一起训练呢用自己debug出来的数据

**Comment by Prinsphield** [comment]
打开teamviewer，告诉我id和passwd，我给你看看？
