### ISSUE TITLE
模型训练的损失问题？作者您好，我没有看明白你网络模型训练过程中没有损失函数，网络的优化是如何实现的，有时间希望解答！非常感谢！

### ISSUE THREAD

**Issue by ZBYuan0813** [Prinsphield/Wechat_AutoJump#94]

**Comment by Prinsphield** [comment]
fine网络的loss在[这里](https://github.com/Prinsphield/Wechat_AutoJump/blob/master/cnn_coarse_to_fine/config/base.fine/train.py#L52)

coarse网络的loss在[这里](https://github.com/Prinsphield/Wechat_AutoJump/blob/master/cnn_coarse_to_fine/config/base.large/train.py#L37)

**Comment by ZBYuan0813** [comment]
非常感谢！！！
