### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by tonywang1990** [Prinsphield/Wechat_AutoJump#95]
nn_play.py reporting this error
`NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for resource/train_logs_coarse/best_model.ckpt-13999
`
It seems the the self.ckpt and self.ckpt_fine in class WechatAutoJump are both pointing the files that doesn't exist. 

Thanks for the help!

**Comment by Dinxin** [comment]
You need to download train log or data that are given on the Baidu Drive or Google Drive.
