### ISSUE TITLE
运行出错，百度无法解决，请帮助！

### ISSUE THREAD

**Issue by 1371030** [Prinsphield/Wechat_AutoJump#96]
python nn_play.py --phone Android --sensitivity 2.045
RuntimeError: module compiled against API version 0xc but this version of numpy is 0x9
Traceback (most recent call last):
  File "nn_play.py", line 8, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import

**Comment by 1371030** [comment]
python -V
Python 2.7.10

**Comment by 1371030** [comment]
/usr/local/Cellar/numpy/1.14.0/bin/f2py
/usr/local/Cellar/numpy/1.14.0/bin/f2py3.6
/usr/local/Cellar/numpy/1.14.0/lib/python2.7/ (411 files)
/usr/local/Cellar/numpy/1.14.0/lib/python3.6/ (411 files)
/usr/local/Cellar/numpy/1.14.0/libexec/nose/ (112 files)

**Comment by Prinsphield** [comment]
你是`brew install opencv3`的吗?安装完应该python3的正常能用，你可以试试python3，python2
的安装完会提示一句话，我记不清了，应该是把`/usr/local/Cellar/opencv/3.4.0/lib/python2.7/site-packages/cv2.so`链到`/usr/local/lib/python2.7/site-packages`下面

**Comment by 1371030** [comment]
brew install opencv3
Warning: opencv 3.4.0_1 is already installed

pwd
/Library/Python/2.7/site-packages
cv2.so -> /usr/local/Cellar/opencv/3.4.0_1/lib/python2.7/site-packages/cv2.so

python3 nn_play.py --phone Android --sensitivity 2.045
Traceback (most recent call last):
  File "nn_play.py", line 8, in <module>
    import cv2
ImportError: dlopen(/Library/Python/2.7/site-packages/cv2.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Library/Python/2.7/site-packages/cv2.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/cv2.so

**Comment by Prinsphield** [comment]
你用`python2`啊

不行用conda吧

**Comment by leon332157** [comment]
pip install opencv

**Comment by leon332157** [comment]
python 又不能使用unix库

**Comment by leon332157** [comment]
如果不行就网上找opencv

**Comment by leon332157** [comment]
你用python3试试

**Comment by leon332157** [comment]
谷歌来的
pip install opencv-python

**Comment by liangyihuai** [comment]
到这里下载open cv3安装包（[http://www.lfd.uci.edu/~gohlke/pythonlibs/](http://www.lfd.uci.edu/~gohlke/pythonlibs/)），我的电脑为：opencv_python-3.4.0+contrib-cp35-cp35m-win_amd64.whl。使用`pip install xxxx.whl`命令安装。

我的电脑的python环境为Anaconda3

**Comment by leon332157** [comment]
@1371030 pip install numpy
