### ISSUE TITLE
用iphone6跑起来了，但是分数不理想

### ISSUE THREAD

**Issue by yuhaozhuang93** [Prinsphield/Wechat_AutoJump#97]
能跑起来，iPhone6，但是最高只有73.基本是10-20就挂了。是不是系数不对？我应该怎么调整呢？我用的是readme里的2.045

**Comment by yuhaozhuang93** [comment]
感觉有时候跳得远，有时候跳的近，好像有些方块不认识，直接跳的很轻就挂了

**Comment by Prinsphield** [comment]
用`nn_play.py`试试

**Comment by yuhaozhuang93** [comment]
就是用的nn_play试的，play根不理想哈哈

**Comment by Prinsphield** [comment]
你打开teamviewer，告诉我id和passwd，我远程给你看看。

**Comment by yuhaozhuang93** [comment]
633 097 049
54xv1j

**Comment by Prinsphield** [comment]
密码无效！

**Comment by yuhaozhuang93** [comment]
有效的吧，好像连上了

**Comment by Prinsphield** [comment]
能wechat吗，网速有点卡，我id: Prinsphield
