### ISSUE TITLE
ios运行出错

### ISSUE THREAD

**Issue by dannyzhou97** [Prinsphield/Wechat_AutoJump#98]
请问这是什么问题啊
![screen shot 2018-01-24 at 00 07 36](https://user-images.githubusercontent.com/22454238/35321000-a1f6d062-009a-11e8-8eb3-0d3e89727e2d.png)

**Comment by Prinsphield** [comment]
按照教程安装wda，并走流程https://testerhome.com/topics/7220

**Comment by dannyzhou97** [comment]
解决了，我需要iproxy 8100 8100就行了
